support for Node.js 12
flatiron/union pull request #64
Opened 2019-06-04 05:36 UTC by Xmader

It does not work on Node.js 12

```
[DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
[DEP0066] DeprecationWarning: OutgoingMessage.prototype._headerNames is deprecated
```

https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_headers_outgoingmessage_headernames

2020-02-15 05:51 UTC, peteriman commented on lib/response-stream.js
> +      this.response._headerNames = this.response._headerNames || {};
Shouldn't this be in another try-catch?

```
// Patch to node core
try {
  this.response._headerNames = this.response.getHeaderNames () || {};
} catch (err) {
  this.response._headerNames = this.response._headerNames || {};  
}
```

2020-02-20 08:44 UTC, kefir01 commented
When can we expect this patch to be published?

2021-06-03 16:46 UTC, Saeger requested changes
Include @peteriman suggestion

2021-09-19 15:36 UTC, peteriman commented
@Xmader Mind making the suggested changes?

2023-12-02 00:18 UTC, mirabilos commented
ping?

2024-01-14 20:58 UTC, lamweili commented
It has been >2 years and @Xmader's hasn't made the suggested changes.
@darrendatbui has made the changes in PR #77 which superseded this PR.
Let's continue there and close this PR.

@indexzero @jcrugzz

2024-01-15 08:18 UTC, lamweili commented on lib/response-stream.js
> +      this.response._headerNames = this.response._headerNames || {};
It has been commented in PR #77 that there is no need for this suggestion.
@darrendatbui has did some testing and the original committed code works.

I rest my case.

2024-01-15 08:18 UTC, lamweili approved these changes

2024-01-18 04:36 UTC, indexzero commented
Appreciate everyone trying to keep this code alive

2024-01-18 04:36 UTC, merged